### ISSUE TITLE
Problem with workers transfering

### ISSUE THREAD

**Issue by Matuiss2** [Matuiss2/JackBot#144]
Sometimes workers from extractors gets transferred to the natural and doesn't get refilled, delaying a lot the zergling speed, which delays a lot the BO after #142

**Comment by tweakimp** [comment]
Pls provide a replay

**Comment by tweakimp** [comment]
[Queda_Cerulea_LE.zip](https://github.com/Matuiss2/Greedy_bot/files/2506457/Queda_Cerulea_LE.zip)
To me, the problem looks like the problem is that we make a random worker slide to the natural, without a 
reason. There were 104 gas mined, but the last 8 were not returned.

**Comment by Helfull** [comment]
the 104 are totally fine for mboost. once i am home i check this replay too.

**Comment by Matuiss2** [comment]
I think I found the cause, it happens when there's a scouting worker and the drones from vespene go to counter that, and then the natural finishes and these drones get transferred to the natural (since they re the closest ones due to being pulled) ...this just happens vs madbot so its just a series of unlucky timings.

The problem is that they don't get refilled

**Comment by tweakimp** [comment]
but tehre was just one worker, why would we pull all drones?

**Comment by Matuiss2** [comment]
We pulled 2 as we should, they were the ones that were on the extractor, ofc I could be totally wrong and the cause could be other, but it just happens vs madbot and the only thing different from that point is this scouting worker

**Comment by Helfull** [comment]
the gas was 96
