### ISSUE TITLE
When retreating, our units take the shortest route even if it's through the enemy army.

### ISSUE THREAD

**Issue by nikgrosland** [Matuiss2/JackBot#171]
If our units get overwhelmed and are ordered to retreat, they sometimes run straight into the enemy army, killing themselves. They should probably try to avoid the enemy army when retreating instead of running straight through it.

**Comment by Matuiss2** [comment]
I spotted that too, but the only way I saw to fix it was checking the pathing grid to the retreat point, which is forbidden to use on the ladder, maybe we can find a better legal way?

**Comment by Matuiss2** [comment]
Might be impossible to fix, Ill be closing this for now
